capacitor-community/camera-preview

README.md
a little bit fix on readme that make me lost one hour
=> fix on import

ios/Plugin/CameraController.swift, ios/Plugin/Plugin.swift, src/definitions.ts
Please added some minor enhancements (return error details etc.)
=> Fixed to make the plugin work on iPhone 6S plus

README.md, android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java, ios/Plugin/Plugin.swift, package-lock.json, package.json, src/definitions.ts
Enabled paddingBottom and rotateWhenOrientationChanged params (see details in src/definition.ts file)
=> Feat preview padding support

README.md, android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java, src/definitions.ts
Fixes #49 
I haven't tested this yet. But it should work. (I can only test this tomorrow)
=> fix(android): add toBack boolean to startCamera

README.md, ios/Plugin/Plugin.swift, src/definitions.ts
add toBack and origin to `startCamera`
=> feat: add toBack, x and y to iOS

android/src/main/java/com/ahm/capacitor/camera/preview/CameraActivity.java
@arielhernandezmusa Please test it before merging if possible.
Closes #57
=> fix: android landscape orientation of clicked images

android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java, ios/Plugin/Plugin.swift
I added the ability to capture image and store it to file on iOS and respected the option on android (it was already working but it always set to false)
Add to this, I added `DispatchQueue.main.async {}` on capture func so that it is not as slow on iOS 14+.
=> add storeToFile option

README.md, package-lock.json, src/definitions.ts, src/web.ts
=> Add support for disabling audio streams on web

android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java
The fix for the issue as described here https://github.com/capacitor-community/camera-preview/issues/65
=> Fix prevent plugin to use audio permission

ios/Plugin/Plugin.swift
The fix for this issue https://github.com/capacitor-community/camera-preview/issues/131
=> Fixed padding bottom param is not working under i os

ios/Plugin/CameraController.swift, ios/Plugin/Plugin.m, ios/Plugin/Plugin.swift
Hello
This is just a draft of the video recording for iOS. I know this is far from perfect and could be improved upon, but it works for me and feels like a good start. Hoping someone else can take it back and make it better :)
=> Start recording ios

android/src/main/java/com/ahm/capacitor/camera/preview/CameraActivity.java, android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java, android/src/main/java/com/ahm/capacitor/camera/preview/CustomTextureView.java, android/src/main/java/com/ahm/capacitor/camera/preview/Preview.java, src/definitions.ts, src/web.ts
Added opacity control for web and Android.  Suitable for AR type projects.
Also added pinch/zoom for Android.  This works for both toBack options (true, false),
=> Opacity and zoom for android  rebased for capacitor-3

README.md
Documenting the addition from PR #87
=> Add documentation of enableHighResolution

README.md, ios/Plugin/CameraController.swift, ios/Plugin/Plugin.swift
Based on #162 from [luckyboykg](https://github.com/luckyboykg) this pull request adds the features
- Pinch to zoom
- Tap to focus
for iOS platform and should solve #143, #158 and #192
=> Add tap to focus and pinch to zoom for iOS

ios/Plugin/CameraController.swift, ios/Plugin/Plugin.swift
resolve conflict from long time PR needed for fix landscape issue:
https://github.com/capacitor-community/camera-preview/pull/130
this is published on npm too to wait until the merge happen :
https://www.npmjs.com/package/@forgr/camera-preview
=> Fix landscape issue

android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java
See the detailed explanation here https://github.com/ryaa/camera-preview/blob/5910c0fdd7f70fecbbe8937e8dabea24fd8fe8b6/android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java#L369
=> bugfix: added the fix to prevent camera is not running error

README.md
Web platform will work only if we follow this instructions : https://github.com/capacitor-community/camera-preview/issues/2#issuecomment-522702654
So i updated the README with it
=> doc: update the web instructions

ios/Plugin/CameraController.swift
See https://github.com/capacitor-community/camera-preview/issues/232
=> bugfix: fixed the problem when photos taken in the landscape orientation are off

package-lock.json, package.json
It should be a peer dependency, not a dependency
=> chore: Make @capacitor/core a peer dependency

src/web.ts
closes https://github.com/capacitor-community/camera-preview/issues/197
=> fix(web): Remove deprecated registerWebPlugin

README.md, demo/src/index.tsx
closes https://github.com/capacitor-community/camera-preview/issues/94
=> docs(README): Add Capacitor 5 version notes

.prettierignore, android/src/main/java/com/ahm/capacitor/camera/preview/CameraActivity.java, android/src/main/java/com/ahm/capacitor/camera/preview/Preview.java, ios/Plugin/CameraController.swift, ios/Plugin/Plugin.swift, ios/PluginTests/PluginTests.swift, src/web.ts
Ran `npm run fmt` excluding the new example app from eslint and prettier.
Added a exception for x and y being too short as that was causing a serious violation.
=> chore: run fmt

.github/workflows/ci.yml
lint fails because of a serious violation, fixed in https://github.com/capacitor-community/camera-preview/pull/371
=> chore(ci): run lint and verify
