capacitor-community/camera-preview

CapacitorCommunityCameraPreview.podspec

This should fix this issue https://github.com/capacitor-community/camera-preview/issues/37

Fix for No podspec found error after plugin rename

---

package.json

package.json files referenced the previous file name so the new renamed file was not included into the published npm package.

Fix for CapacitorCommunityCameraPreview.podspec not included into npm package published

---

src/definitions.ts
src/web.ts

Hi, I added definitions for flip() method in CameraPreview interface. Also I added a default stub implementation for that method in the web platform (actually throws an error like other not supported methods).

Fix definitions

---

src/web.ts

Hi, Since`start()` looks for a video element and if it doesn't exists. It creates a video element, else throws `camera already started`.
While restarting the camera since `stop()` doesn't remove the element. It was throwing the same.
I fixed this, so the video element is now removed properly in `stop()`.

fix(CameraPreviewWeb): remove video element from parent

---

android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java
src/definitions.ts

added origin (x, y) to startCamera for android. So now we can add the CameraPreview over a div or on specific place on the screen.
```
getBridge().getWebView().getParent().bringChildToFront(getBridge().getWebView());
```
Removed this line not sure what it does. But seems deprecated and hinders the preview for Ionic React.

fix: add origin (x,y) to startCamera

---

ios/Plugin/Plugin.swift
src/web.ts

laterally inverts image taken from webcam or front cam in iOS.
For android it's already there. Adding some consistency :wink:

fix:image lateral inversion for webview and ios

---

ios/Plugin/Plugin.swift

This PR fixes querying for the wrong parameter name for the `toBack` parameter.
Fixes #61

Changed wrong parameter name

---

ios/Plugin/CameraController.swift

Currently this wasn't supported so in faceUp and faceDown orientation.
The default was `portrait`. Now it takes the statusBarOrientation.

fix: amend orientation to support faceUp and faceDown

---

ios/Plugin/Plugin.swift
src/web.ts

If permission is not granted. There was no unified way to catch this and show a fallback UI.
Changes already exists for android. Needed this to be implemented for iOS and webview.
Now you can do 
```
await CameraPreview.start({
...
}).catch(({ message }: { message: string }) => {
if (message === 'permission failed') {
// Show fallback ui or do something.
}
});
```

fix: add permission check and reject call

---

ios/Plugin/Plugin.swift

I found that when setting `toBack: true` in the `CameraPreviewOptions` the preview couldn't be seen. I suspected the elements within the webview were not transparent, but after setting all I could using CSS I was still unable to see the preview.
Searching the web I found that a line from solution 1 of [this article on izzi swift](https://izziswift.com/transparent-background-for-wkwebview/) where they suggest setting the `scrollView.backgroundColor` to transparent which worked! Finally the preview underneath the webview was visible! 🎉 
I believe this solves issue #53

Ensure background of webview on iOS is transparent

---

README.md
android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java
src/definitions.ts

If width and height are not specified or are 0 it will use the defaults. If width and height are specified, it will choose a supported photo size that is closest to width and height specified and has closest aspect ratio to the preview.

Android Image Dimensions

---

README.md

This PR is to update the README with the additional installation step `npx cap sync`.
I had some very confusing errors because I had forgotten to run `npx cap sync` after installation. Yes, I know it seems obvious, but those who are new to Ionic (such as myself) may not remember/know that they need to run this after the installation of a plugin.
Thanks for the great work on this plugin!

Update README with `npx cap sync`

---

README.md
android/build.gradle
android/src/main/java/com/ahm/capacitor/camera/preview/CameraActivity.java
android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java
src/definitions.ts

Performing some tests and after sending the image to a web service, the image always remained in landscape mode, even removing changes in orientation.
Researching a little about, I identified that the problem happens due to the image metadata.
I included in the plugin the disableExifHeaderStripping option as a boolean, keeping the default value true as before.

Camera Orientations - disableExifHeaderStripping

---

ios/Plugin/Plugin.swift

There was a bad API usage of jpegData. Value must be between 0 and 1:
https://developer.apple.com/documentation/uikit/1624115-uiimagejpegrepresentation?language=swift
```
compressionQuality
The quality of the resulting JPEG image, expressed as a value from 0.0 to 1.0. The value 0.0 represents the maximum compression (or lowest quality) while the value 1.0 represents the least compression (or best quality).
```
This PR aims to fix this issue.

fix: compressionQuality is between 0 and 1 in jpegData

---

ios/Plugin/CameraController.swift
ios/Plugin/Plugin.swift
package.json
src/definitions.ts

For now images taken with an Apple device are limited in resolution. I've added a flag to activate high resolution capture, allowing users to take full resolution pictures.
Also added a prepare step for npm so that the plugin is correctly built when installed from github.

Enable high resolution capture on iOS

---

package.json

The npm package `rimraf` is used to make the remove action more abstract and also allows it to work on Windows and everywhere else where `rm` is not available.

Fix non-available rm command

---

README.md
src/web.ts

Consuming `options.position` in web portion of the plugin so rear camera can be accessed on mobile devices.
Using [facingMode: environment](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode), which will select an environment facing camera if there is one. Desktop still resorts to webcam.
Could fix #43 , I can't tell if the issue is directly related to web, android, or both?

Web rear facing camera

---

README.md
android/src/main/java/com/ahm/capacitor/camera/preview/CameraPreview.java

This PR adds an option to the `start()` call: `lockAndroidOrientation`.
The goal of this option is to provide a workaround for issues seen when rotating an android device while the camera preview is showing (#93, #107).

add lockAndroidOrientation option

---

ios/Plugin/Plugin.swift

This PR fixes an issue when capturing an image after calling `CameraPreview.flip()`. 
Bug description:
When starting the front camera the captured image is always flipped, even after switching to rear, viceversa when starting the rear camera and switching to front the captured image is not flipped.

fix iOS capture flipped image after camera flip

---

src/web.ts

`videoElement.play()` throws a NotAllowedError if `autoplay`, `muted` and `playsinline` are not set on iOS Safari. Adding check for safari and apply attributes as necessary.

iOS Safari additional attributes needed

---

package-lock.json
package.json

Because the Capacitor dependency was set up to use the latest version available it would incorrectly depend on Capacitor 3 which is not yet supported by this plugin. This PR fixes the Capacitor version to 2.4.7.

Fixed capacitor version

---

ios/Plugin/Plugin.swift

Hey @pbowyer, I was doing some more with the Capacitor 3 upgrade and I noticed that the underlying promise for iOS permissions resolves before the prompt is answered by the user. If the user is doesn't answer the prompt right away.
I'm fixing that here by moving the `DispatchQueue.main.async` within the callback of `AVCaptureDevice.requestAccess`.

Moving camera preparation into the callback of `requestAccess`. 

---

ios/Plugin/Plugin.swift

X and Y options are ignored in function start. With these changes default values are x=0, y=0 but it takes what it cames on parameters.

iOS - always starts on position x=0 y=0

---

android/build.gradle

As say here : https://capacitorjs.com/docs/updating/3-0#update-gradle-to-70
Gradle 7 is the minium version for android, in capacitor 3.
- [jcenter become deprecated](https://docs.gradle.org/current/userguide/upgrading_version_6.html)
- [`compile` have been removed](https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal)

fix: Gradle 7 builds for capacitor 3 as recommended

---

ios/Plugin/CameraController.swift
ios/Plugin/Plugin.swift

On iOS, if you enable the camera preview while the device is in landscape and rotate the device to portrait, the preview layer's  width and height are reversed and the preview only appears to take up half the screen.

Fix camera display on iOS when rotated after opening in landscape

---

README.md
ios/Plugin/CameraController.swift
ios/Plugin/Plugin.swift

Fixes issue #191 by disabling audio on iOS, if the `disableAudio` option is enabled. Therefore the `NSMicrophoneUsageDescription` permission is optional now.

Fixed microphone permissions request on iOS

---

src/definitions.ts

`flip` and `setFlashMode` are defined as returning `void`, which is not correct. These methods (like all others) return a `Promise`. The wrong return type makes it impossible to catch any errors from these methods without an unsafe cast (`as unknown as Promise<void>`)

Fix wrong return type on `flip` and `setFlashMode`

---

android/src/main/java/com/ahm/capacitor/camera/preview/CameraActivity.java

Implemented the fix to flip/switch between the main front and back cameras and avoid switching to additional cameras.
Before the flip was switching through all the available cameras, so if flip was invoked twice and there were more then 2 cameras available (for example, on my Samsung A53 there are 4 cameras total), the second flip did not return to the initial camera.

bugfix: getSupportedFlashModes returns array empty in Android 14 SDK 34 #345
